FROM node:22-alpine

WORKDIR /app

# copy package.json
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/web/package.json apps/web/
COPY packages/ packages/

RUN npm install -g pnpm
RUN pnpm install

# copy main files
COPY apps/web apps/web/

# Build your backend
RUN pnpm run buildscript

EXPOSE 3100

CMD [ "pnpm", "run", "docker:web"]